# Generated by Claude Code Bootstrap
# Core makefile with common targets and utilities

### ⇡ GENERATED BLOCK ⇡ DO NOT EDIT
.PHONY: help clean info bootstrap-info

# Default target
.DEFAULT_GOAL := help

# Clean up build artifacts
clean:
	@echo "🧹 Cleaning up build artifacts..."
	rm -rf build/
	rm -rf dist/
	rm -rf node_modules/
	rm -rf .pytest_cache/
	rm -rf __pycache__/
	find . -name "*.pyc" -delete
	find . -name "*.pyo" -delete
	find . -name "*~" -delete
	go clean -cache -testcache -modcache 2>/dev/null || true
	@echo "✅ Clean completed"

# Show build information
info:
	@echo "📋 Build Information:"
	@echo "  Project: $(shell basename $(PWD))"
	@echo "  Generated: $(shell date)"
	@echo "  Bootstrap: Claude Code Bootstrap"
	@echo "  Platform: $(shell uname -s)"

# Show bootstrap information
bootstrap-info:
	@echo "🚀 Bootstrap Information:"
	@echo "  Status: Active"
	@echo "  Configuration: .maestro/makefiles/"
	@echo "  Available platforms: go, node, python, react, docker"
	@echo "  Help: make help"

# Help target (will be overridden by platform-specific makefiles)
help:
	@echo "📖 Available targets:"
	@echo "  help         - Show this help message"
	@echo "  clean        - Clean build artifacts"
	@echo "  info         - Show build information"
	@echo "  bootstrap-info - Show bootstrap information"
	@echo ""
	@echo "Platform-specific targets will be shown when available."
### ⇣ GENERATED BLOCK ⇣ DO NOT EDIT
