# Generated by Claude Code Bootstrap
# Go-specific build targets

### ⇡ GENERATED BLOCK ⇡ DO NOT EDIT
.PHONY: go-build go-test go-lint go-run go-mod go-format go-vet

# Override common targets for Go
build: go-build
test: go-test
lint: go-lint
run: go-run

# Go-specific targets
go-build:
	@echo "🔨 Building Go project..."
	go mod download
	go build ./...
	@echo "✅ Go build completed"

go-test:
	@echo "🧪 Running Go tests..."
	go test ./...
	@echo "✅ Go tests completed"

go-lint:
	@echo "🔍 Running Go linting..."
	@which golangci-lint > /dev/null || (echo "golangci-lint not found, using go vet" && go vet ./...)
	@which golangci-lint > /dev/null && golangci-lint run ./...
	@echo "✅ Go linting completed"

go-run:
	@echo "🚀 Running Go application..."
	go run .

go-mod:
	@echo "📦 Updating Go modules..."
	go mod tidy
	go mod download
	@echo "✅ Go modules updated"

go-format:
	@echo "🎨 Formatting Go code..."
	go fmt ./...
	@echo "✅ Go formatting completed"

go-vet:
	@echo "🔍 Running go vet..."
	go vet ./...
	@echo "✅ Go vet completed"

go-help:
	@echo "🐹 Go targets:"
	@echo "  go-build     - Build Go project"
	@echo "  go-test      - Run Go tests"
	@echo "  go-lint      - Run Go linting"
	@echo "  go-run       - Run Go application"
	@echo "  go-mod       - Update Go modules"
	@echo "  go-format    - Format Go code"
	@echo "  go-vet       - Run go vet"
	@echo ""
### ⇣ GENERATED BLOCK ⇣ DO NOT EDIT
